"""Validated modifier-tap profiles, without rewriting the user's binding files."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

from adws_i18n import tr as _tr
from adws_niri_compat import niri_binary

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ('waylander', 'traditional', 'reversed')
BEGIN = '// ==== ADWS keyboard profile BEGIN ===='
END = '// ==== ADWS keyboard profile END ===='
PATTERN = re.compile(r'(?m)^' + re.escape(BEGIN) + r'\n// profile: (waylander|traditional|reversed)\ninclude "([^"\n]+)"\n' + re.escape(END) + r'\n?')


def modifier_taps_supported():
    """Probe grammar, rather than assuming a version number identifies a fork."""
    niri = niri_binary()
    if not niri:
        return False
    try:
        with tempfile.TemporaryDirectory(prefix='adws-keyboard-probe-') as directory:
            probe = Path(directory) / 'config.kdl'
            probe.write_text(bindings('traditional'))
            return subprocess.run([niri, 'validate', '-c', str(probe)], capture_output=True, timeout=2).returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def current_profile(path=None):
    from adws_windows import config_path
    path = Path(path) if path else config_path()
    text = path.read_text() if path.exists() else ''
    match = PATTERN.search(text)
    return match[1] if match else 'waylander'


def clean_block(text):
    matches = list(PATTERN.finditer(text))
    if text.count(BEGIN) != len(matches) or text.count(END) != len(matches) or len(matches) > 1:
        raise ValueError(_tr('ADWS 键位配置标记不完整，请检查 Niri 配置。'))
    return PATTERN.sub('', text)


def bindings(profile, root=ROOT):
    if profile not in PROFILES:
        raise ValueError(_tr('未知键位方案。'))
    start = 'spawn "bash" ' + json.dumps(str(root / 'adws'), ensure_ascii=False) + ' "start-menu";'
    overview = 'toggle-overview;'
    # An empty spawn explicitly shadows the prior Ctrl tap. Niri returns
    # immediately for an empty command without creating a child process.
    super_action, ctrl_action = {
        'waylander': (overview, 'spawn;'),
        'traditional': (start, overview),
        'reversed': (overview, start),
    }[profile]
    # Mod and Super are distinct config keys but can match the same physical key.
    # Override both to prevent the original Mod tap winning by iteration order.
    return ('// Generated by ADWS. Modifier taps only; combinations are unchanged.\n'
            'binds {\n'
            f'    Mod repeat=false hotkey-overlay-title=null {{ {super_action} }}\n'
            f'    Super repeat=false hotkey-overlay-title=null {{ {super_action} }}\n'
            f'    Ctrl repeat=false hotkey-overlay-title=null {{ {ctrl_action} }}\n'
            '}\n')


def apply_profile(profile, path=None, root=ROOT):
    from adws_windows import config_path
    from adws_atomic import replace_files
    path = (Path(path) if path else config_path()).resolve()
    niri = niri_binary()
    if not niri:
        raise ValueError(_tr('未找到 Niri，无法校验键位方案。'))
    old = path.read_text()
    cleaned = clean_block(old)
    content = bindings(profile, root)
    digest = hashlib.sha256(content.encode()).hexdigest()[:20]
    included = path.parent / ('.adws-keyboard-' + digest + '.kdl')
    # Immutable includes keep the running configuration valid until the main
    # config can be replaced atomically. Never overwrite another profile file.
    created = not included.exists()
    if not created and included.read_text() != content:
        raise ValueError(_tr('ADWS 键位文件发生冲突，未修改配置。'))
    temporary = None
    committed = False
    try:
        if created:
            with included.open('x') as stream:
                stream.write(content)
        updated = cleaned.rstrip() + '\n\n' + BEGIN + '\n// profile: ' + profile + '\ninclude ' + json.dumps(included.name) + '\n' + END + '\n'
        with tempfile.NamedTemporaryFile(mode='w', suffix='.kdl', prefix='.adws-keyboard-check-', dir=path.parent, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(updated)
        try:
            result = subprocess.run([niri, 'validate', '-c', str(temporary)], capture_output=True, text=True, timeout=5)
        except subprocess.TimeoutExpired as exc:
            raise ValueError(_tr('Niri 键位校验超时，未修改配置。')) from exc
        if result.returncode:
            raise ValueError(_tr('此 Niri 配置不支持该键位方案，未修改配置：\n') + (result.stderr or result.stdout).strip())
        if path.read_text() != old:
            raise ValueError(_tr('Niri 配置已被其他程序修改，请重试。'))
        if updated != old:
            shutil.copy2(path, path.with_suffix(path.suffix + '.adws-keyboard-bak'))
            replace_files({path: updated.encode()})
        committed = True
    finally:
        if temporary:
            temporary.unlink(missing_ok=True)
        if created and not committed:
            included.unlink(missing_ok=True)
